### ISSUE TITLE
Codecov migration to marketplace app

### ISSUE THREAD

**Issue by thomasrockhu** [sensuikan1973/HumanLifeGame#158]
Hi, Tom from [Codecov](https://codecov.io) here.

We noticed that you are using Codecov with fairly high frequency, and we’re so excited to see that! However, because you are not using our app, you may have experienced issues with uploading reports or viewing coverage information. This is due to rate-limiting issues from GitHub.

**In order to prevent any future outages, we ask that you move over to our [GitHub app integration](https://github.com/apps/codecov).**

The process is extremely simple and shouldn’t require more than a few clicks, and you should not expect any downtime. By moving to our app, you will no longer need an admin or separate account to manage the relationship with GitHub as the team bot.

Let me know if you have any questions, or if I can help at all with this process.

**Comment by sensuikan1973** [comment]
Thanks!

**Comment by sensuikan1973** [comment]
done
![image](https://user-images.githubusercontent.com/23427957/83495395-98c04600-a4f2-11ea-8cba-5a699199c52f.png)

I will wait and see

**Comment by sensuikan1973** [comment]
I appreciate it very much. 👍 

for now, there is no problem. so, close this.

**Comment by sensuikan1973** [comment]
sorry, there is still problem.
https://github.com/sensuikan1973/HumanLifeGame/pull/167 will resolve this.
